# Generated by Django 5.0 on 2023-12-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brewstep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.IntegerField()),
                ('change_in_water', models.CharField(max_length=50)),
                ('change_in_time', models.CharField(max_length=50)),
            ],
        ),
    ]
