# Generated by Django 5.0 on 2023-12-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewstep',
            name='change_in_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='brewstep',
            name='change_in_water',
            field=models.IntegerField(),
        ),
    ]
