# Generated by Django 5.0 on 2023-12-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0002_alter_brewstep_change_in_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewstep',
            options={'ordering': ['step_id']},
        ),
        migrations.AddField(
            model_name='brewstep',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
