# Generated by Django 5.0 on 2023-12-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0004_rename_my_order_brewstep_display_step_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brewstep',
            name='display_step_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='brewstep',
            name='step_id',
            field=models.PositiveIntegerField(),
        ),
    ]
