# Generated by Django 5.0 on 2023-12-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0006_remove_brewstep_display_step_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brewstep',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
