# Generated by Django 5.0 on 2023-12-29 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0008_recipe_brewstep_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_id']},
        ),
        migrations.AlterField(
            model_name='brewstep',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='brewhelper.recipe'),
        ),
    ]
