# Generated by Django 5.0 on 2023-12-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0009_alter_recipe_options_alter_brewstep_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brewstep',
            old_name='recipe',
            new_name='recipeID',
        ),
    ]
