# Generated by Django 5.0 on 2023-12-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0011_recipe_coffee_grind_size_recipe_coffee_grind_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coffee_grind_weight',
            new_name='coffee_weight',
        ),
    ]
