# Generated by Django 5.0 on 2023-12-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0012_rename_coffee_grind_weight_recipe_coffee_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('recipes', models.ManyToManyField(related_name='methods', to='brewhelper.recipe')),
            ],
        ),
    ]
