# Generated by Django 5.0 on 2024-01-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0013_brewmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reference',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='brewstep',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
