# Generated by Django 5.0 on 2024-01-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0016_remove_brewstep_id_alter_brewstep_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='methods',
        ),
        migrations.AddField(
            model_name='brewmethod',
            name='recipes',
            field=models.ManyToManyField(related_name='methods', to='brewhelper.recipe'),
        ),
    ]
