# Generated by Django 5.0 on 2024-01-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0019_alter_recipe_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='brewmethod',
            name='equipment',
            field=models.ManyToManyField(related_name='brewmethods', to='brewhelper.equipment'),
        ),
    ]
