# Generated by Django 5.0 on 2024-02-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0020_equipment_brewmethod_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
