# Generated by Django 5.0 on 2024-02-04 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brewhelper', '0022_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='coffee_weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
